FROM node:10
  
ENV PORT 3000

ENV NODE_HEAPDUMP_OPTIONS nosignal

# Install OS updates
RUN apt-get update && apt-get install bc \
 && echo 'Finished installing dependencies'

WORKDIR "/app"

COPY run-dev /bin
COPY run-debug /bin

RUN chmod 777 /bin/run-dev /bin/run-debug

# Install nodemon for use with "dev" mode
RUN npm install nodemon

# Bundle app source and install dependencies
COPY . /app
RUN npm install

EXPOSE 3000

USER node

CMD ["/bin/bash"]
